# Generated by Django 6.1 on 2026-08-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.CharField(blank=True, help_text='e.g. A4, A5', max_length=200),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI (Google Pay / PhonePe / Paytm)'), ('CARD', 'Credit / Debit Card'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Digital Wallet')], default='UPI', max_length=30)),
                ('transaction_reference', models.CharField(max_length=30, unique=True)),
                ('ticket_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=30.0, max_digits=8)),
                ('taxes', models.DecimalField(decimal_places=2, default=54.0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
