# Generated by Django 6.0.7 on 2026-08-18 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_payment_status_booking_selected_seats_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(db_index=True, help_text='e.g. A1, E4', max_length=10)),
                ('status', models.CharField(choices=[('RESERVED', 'Temporarily Reserved'), ('BOOKED', 'Confirmed & Booked')], default='RESERVED', max_length=20)),
                ('reserved_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_reservations', to='booking.booking')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='booking.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['show', 'seat_number'],
                'indexes': [models.Index(fields=['show', 'status', 'reserved_until'], name='booking_sea_show_id_6f52eb_idx'), models.Index(fields=['reserved_until'], name='booking_sea_reserve_4ef267_idx')],
                'unique_together': {('show', 'seat_number')},
            },
        ),
    ]
