# Generated by Django 6.0.7 on 2026-08-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castmember',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Remote photo URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='image_type',
            field=models.CharField(choices=[('poster', 'Poster'), ('backdrop', 'Backdrop'), ('gallery', 'Gallery')], default='poster', max_length=20),
        ),
        migrations.AddField(
            model_name='movieimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Remote image URL (e.g. TMDB or CDN)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movieimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
